# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df5d7d6fa487158164ed6e569c0c7425b6ce9d1ac43b46ed42761401ea6d2f03e8b75b4533d038a0eb31289bd507f02976e3785d1212f5da4ff9c0ad0f99695

test:
  secret_key_base: f36bee3e8496e29bc1ec868b7befcc023614735605dc71b37a62384a2c674216fef86f5fe66d68f7264d07d4d87e4699d5e4de19e17ca7edf80e53184b4b57d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
